name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Initialize GNU build system
      run: autoreconf -i -s
    - name: Create build configuration
      run: ../configure
      working-directory: ./build
    - name: Build
      run: make
      working-directory: ./build
    - name: Tests
      run: make check
      working-directory: ./build

#    - name: make distcheck
#      run: make distcheck
