name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Initialize GNU build system
      run: autoreconf -i -s
      working-directory: bison/final
    - name: Create build configuration
      run: ../configure YACC=bison CXX=g++-13
      working-directory: bison/final/build
    - name: Build
      run: make
      working-directory: bison/final/build
    - name: Tests
      run: make check
      working-directory: bison/final/build

#    - name: make distcheck
#      run: make distcheck
